services:

  mysql:
    image: mysql:5.5.48
    container_name: mysql
    restart: always
    env_file:
      - .env
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
        - ./master:/master
    # command: mysql -uroot -proot master < master/master.sql

  nacional:
    build:
      context: .
      dockerfile: Dockerfile-slim
    container_name: nacional
    restart: always
    network_mode: "host"
    # ports:
    #     - "9000:9000"
    #     - "8080:8080"
    depends_on:
        - mysql