FROM amazoncorretto:8u412-alpine3.16

WORKDIR /server

COPY client /client
COPY server /server
COPY java /java

RUN apk add mysql-client

# Hacer que el contenedor corra nacional_server.jar con los parámetros de memoria especificados
CMD ["java", "-Xms128M", "-Xmx256M", "-jar", "nacional_server.jar"]
