services:

  mysql:
    #image: mysql:5.5.48 # Es la versión original que matchea con nacional, no funciona la opción de Backups
    # image: mariadb:10.11.7 # Varsión de MariaDB funcional, si se usa se debe modificar el script del listador
    image: mariadb:10.6.16 # Varsión de MariaDB funcional, si se usa se debe modificar el script del listador
    container_name: mysql
    restart: always
    env_file:
      - .env
    command:
      - --bind-address=0.0.0.0
      - --character-set-server=latin1
      - --collation-server=latin1_swedish_ci
      - --sql-mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    ports:
        - "3306:3306"
    volumes:
        - nacional_dbdata:/var/lib/mysql
        - ./master:/master
        - ./backups:/backups
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  nacional:
    build:
      context: .
      dockerfile: Dockerfile-slim
    container_name: nacional
    restart: always
    network_mode: "host"
    # ports:
    #     - "9000:9000"
    #     - "8080:8080"
    volumes:
        - ./server:/server
        - ./client:/client
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  nacional_dbdata:
